
    const events = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: '',
            name: 'Sponsors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: '',
            name: 'Mentors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547857800000,
            location: '',
            name: 'Hacker Check-In',
            startTime: 1547850600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: '',
            name: 'Bolay Dinner',
            startTime: 1547852400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: '',
            name: 'Team Building Activity',
            startTime: 1547854200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547863200000,
            location: '',
            name: 'Opening Ceremony',
            startTime: 1547859600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547866800000,
            location: '',
            name: 'Sponsor Fair',
            startTime: 1547863200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: null,
            location: '',
            name: 'Hacking Begins!!',
            startTime: 1547866800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: '',
            name: 'SwampTank Activity',
            startTime: 1547869500000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: '',
            name: 'Git Workshop',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547872500000,
            location: '',
            name: 'Survival Guide/Spring Framework w/ JP Morgan',
            startTime: 1547870400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: '',
            name: 'Midnight Snack from KIND',
            startTime: 1547874000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547876700000,
            location: '',
            name: 'Intro to Frontend (HTML/CSS)',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: '',
            name: 'iOS Development in Swift',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547881200000,
            location: '',
            name: 'VR with Unity',
            startTime: 1547877600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547878800000,
            location: '',
            name: 'Extreme Rock Paper Scissors',
            startTime: 1547877600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547883000000,
            location: '',
            name: 'Ping Pong Tournament',
            startTime: 1547879400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547884800000,
            location: '',
            name: 'Intro to Reverse Engineering',
            startTime: 1547881200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547935200000,
            location: '',
            name: 'RealTruck Workshop',
            startTime: 1547931600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547902800000,
            location: '',
            name: 'Slime Station',
            startTime: 1547899200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547906400000,
            location: '',
            name: 'Flying Biscuit Breakfast',
            startTime: 1547902800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547912700000,
            location: '',
            name: 'Citi Workshop',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: '',
            name: 'Building a Backend with Python and Flask',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917200000,
            location: '',
            name: 'Pancake Art',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: '',
            name: 'Musical Chairs',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919000000,
            location: '',
            name: 'Advanced Frontend (Angular/React)',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917500000,
            location: '',
            name: 'InfoTech Workshop',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919300000,
            location: '',
            name: 'Home Depot Workshop',
            startTime: 1547917200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547922600000,
            location: '',
            name: 'Therapy Dogs',
            startTime: 1547919000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: '',
            name: 'Mi Apa Lunch',
            startTime: 1547920800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: '',
            name: 'Chubby Bunny Game',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Jackbox Games',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547933400000,
            location: '',
            name: 'Dodge Ball',
            startTime: 1547931600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Paper Airplane Comp',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928300000,
            location: '',
            name: 'American Express Workshop',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Machine Learning with Python',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Jackbox Games',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Spicy Ramen Challenge',
            startTime: 1547928000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Lock Picking',
            startTime: 1547929800000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: '',
            name: 'Cup Stacking MLH',
            startTime: 1547933400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: '',
            name: 'Rubik\'s Competition',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: '',
            name: 'Trivia',
            startTime: 1547946000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547953200000,
            location: '',
            name: 'NERF War',
            startTime: 1547949600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547944200000,
            location: '',
            name: 'Piesanoes Dinner',
            startTime: 1547938800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'From Dominoes',
            endTime: 1547964000000,
            location: '',
            name: 'Dominoes Midnight Snack',
            startTime: 1547960400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547965800000,
            location: '',
            name: 'Smash Bros Tournament',
            startTime: 1547962200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: '',
            name: 'Public Breakfast',
            startTime: 1547989200000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547989200000,
            location: '',
            name: 'DevPost Submissions Close',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: '',
            name: 'Demo Practice',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'Prizes given to Winner',
            endTime: 1547994600000,
            location: '',
            name: 'SwampCup Winner Announced',
            startTime: 1547992800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548000000000,
            location: '',
            name: 'Publix Lunch',
            startTime: 1547996400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: null,
            location: '',
            name: 'HACKING ENDS',
            startTime: 1547996400000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548003600000,
            location: '',
            name: 'Demo Fair Round 1',
            startTime: 1547999100000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548009000000,
            location: '',
            name: 'Demo Fair Round 2',
            startTime: 1548004500000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548012300000,
            location: '',
            name: 'VIP Top 3 Deliberations',
            startTime: 1548011700000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548018000000,
            location: '',
            name: 'Closing Ceremonies',
            startTime: 1548012600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548019800000,
            location: '',
            name: 'Buses Depart',
            startTime: 1548019800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
    ];
    
    const fridayEvents = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: '',
            name: 'Sponsors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547856000000,
            location: '',
            name: 'Mentors Check-In',
            startTime: 1547848800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547857800000,
            location: '',
            name: 'Hacker Check-In',
            startTime: 1547850600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: '',
            name: 'Bolay Dinner',
            startTime: 1547852400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547859600000,
            location: '',
            name: 'Team Building Activity',
            startTime: 1547854200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547863200000,
            location: '',
            name: 'Opening Ceremony',
            startTime: 1547859600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547866800000,
            location: '',
            name: 'Sponsor Fair',
            startTime: 1547863200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: null,
            location: '',
            name: 'Hacking Begins!!',
            startTime: 1547866800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: '',
            name: 'SwampTank Activity',
            startTime: 1547869500000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547874000000,
            location: '',
            name: 'Git Workshop',
            startTime: 1547870400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Friday',
            description: '',
            endTime: 1547872500000,
            location: '',
            name: 'Survival Guide/Spring Framework w/ JP Morgan',
            startTime: 1547870400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
    ];

    const saturdayEvents = [
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: '',
            name: 'Midnight Snack from KIND',
            startTime: 1547874000000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547876700000,
            location: '',
            name: 'Intro to Frontend (HTML/CSS)',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547877600000,
            location: '',
            name: 'iOS Development in Swift',
            startTime: 1547874000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547881200000,
            location: '',
            name: 'VR with Unity',
            startTime: 1547877600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547878800000,
            location: '',
            name: 'Extreme Rock Paper Scissors',
            startTime: 1547877600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547883000000,
            location: '',
            name: 'Ping Pong Tournament',
            startTime: 1547879400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547884800000,
            location: '',
            name: 'Intro to Reverse Engineering',
            startTime: 1547881200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547935200000,
            location: '',
            name: 'RealTruck Workshop',
            startTime: 1547931600000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547902800000,
            location: '',
            name: 'Slime Station',
            startTime: 1547899200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547906400000,
            location: '',
            name: 'Flying Biscuit Breakfast',
            startTime: 1547902800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547912700000,
            location: '',
            name: 'Citi Workshop',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547913600000,
            location: '',
            name: 'Building a Backend with Python and Flask',
            startTime: 1547910000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917200000,
            location: '',
            name: 'Pancake Art',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547915400000,
            location: '',
            name: 'Musical Chairs',
            startTime: 1547913600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919000000,
            location: '',
            name: 'Advanced Frontend (Angular/React)',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547917500000,
            location: '',
            name: 'InfoTech Workshop',
            startTime: 1547915400000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547919300000,
            location: '',
            name: 'Home Depot Workshop',
            startTime: 1547917200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547922600000,
            location: '',
            name: 'Therapy Dogs',
            startTime: 1547919000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: '',
            name: 'Mi Apa Lunch',
            startTime: 1547920800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547926200000,
            location: '',
            name: 'Chubby Bunny Game',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Jackbox Games',
            startTime: 1547924400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547933400000,
            location: '',
            name: 'Dodge Ball',
            startTime: 1547931600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Paper Airplane Comp',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928300000,
            location: '',
            name: 'American Express Workshop',
            startTime: 1547926200000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Machine Learning with Python',
            startTime: 1547928000000,
            type: 'workshop',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547928000000,
            location: '',
            name: 'Jackbox Games',
            startTime: 1547926200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Spicy Ramen Challenge',
            startTime: 1547928000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547931600000,
            location: '',
            name: 'Lock Picking',
            startTime: 1547929800000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: '',
            name: 'Cup Stacking MLH',
            startTime: 1547933400000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547937000000,
            location: '',
            name: 'Rubik\'s Competition',
            startTime: 1547935200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547949600000,
            location: '',
            name: 'Trivia',
            startTime: 1547946000000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547953200000,
            location: '',
            name: 'NERF War',
            startTime: 1547949600000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Saturday',
            description: '',
            endTime: 1547944200000,
            location: '',
            name: 'Piesanoes Dinner',
            startTime: 1547938800000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
    ];

    const sundayEvents = [
       {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'From Dominoes',
            endTime: 1547964000000,
            location: '',
            name: 'Dominoes Midnight Snack',
            startTime: 1547960400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547965800000,
            location: '',
            name: 'Smash Bros Tournament',
            startTime: 1547962200000,
            type: 'activity',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: '',
            name: 'Public Breakfast',
            startTime: 1547989200000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547989200000,
            location: '',
            name: 'DevPost Submissions Close',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1547992800000,
            location: '',
            name: 'Demo Practice',
            startTime: 1547989200000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: 'Prizes given to Winner',
            endTime: 1547994600000,
            location: '',
            name: 'SwampCup Winner Announced',
            startTime: 1547992800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548000000000,
            location: '',
            name: 'Publix Lunch',
            startTime: 1547996400000,
            type: 'food',
            winnerSet: false,
            qrNeeded: true,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: null,
            location: '',
            name: 'HACKING ENDS',
            startTime: 1547996400000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548003600000,
            location: '',
            name: 'Demo Fair Round 1',
            startTime: 1547999100000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548009000000,
            location: '',
            name: 'Demo Fair Round 2',
            startTime: 1548004500000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548012300000,
            location: '',
            name: 'VIP Top 3 Deliberations',
            startTime: 1548011700000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548018000000,
            location: '',
            name: 'Closing Ceremonies',
            startTime: 1548012600000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
        {
            attendants: [],
            classification: '',
            company: '',
            day: 'Sunday',
            description: '',
            endTime: 1548019800000,
            location: '',
            name: 'Buses Depart',
            startTime: 1548019800000,
            type: 'general',
            winnerSet: false,
            qrNeeded: false,
        },
    ];
